# Generated by Django 4.0.4 on 2022-05-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogViajes', '0002_suscriptor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Destino',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Reseña',
            new_name='reseña',
        ),
    ]
