# Generated by Django 4.0.4 on 2022-05-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogViajes', '0003_rename_autor_viaje_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('reseña', models.CharField(max_length=400)),
                ('calificacion', models.CharField(max_length=10)),
                ('autor', models.CharField(max_length=20)),
            ],
        ),
    ]
