# Generated by Django 4.0.4 on 2022-05-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogViajes', '0004_aeropuertos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeropuertos',
            name='reseña',
        ),
        migrations.AlterField(
            model_name='aeropuertos',
            name='calificacion',
            field=models.IntegerField(),
        ),
    ]
