# Generated by Django 4.0.4 on 2022-05-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogViajes', '0005_remove_aeropuertos_reseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('calificacion', models.CharField(max_length=2)),
                ('autor', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Aeropuertos',
        ),
    ]
