# Generated by Django 4.0.4 on 2022-05-31 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogViajes', '0006_aeropuerto_delete_aeropuertos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscriptor',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='suscriptor',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='suscriptor',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='imagen',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
